name: dart_learning_journey
description: Data types and variables. Operators and control structures.
version: 0.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2
dependencies:
  talker: ^4.9.1
  meta: ^1.17.0
